### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by reversebro** [NorthenFox/TikTokPy#1]
Traceback (most recent call last):
  File "/Users/fhartavi/Desktop/tiktok2/tiktokpy/example.py", line 1, in <module>
    import tiktokpy
  File "/Users/fhartavi/Desktop/tiktok2/tiktokpy/tiktokpy.py", line 3, in <module>
    from . import api
ImportError: attempted relative import with no known parent package

**Comment by gordienko-dmitry** [comment]
Replace example.py from "tiktokpy/" directory in "/Users/fhartavi/Desktop/tiktok2/"

**Comment by reversebro** [comment]
Traceback (most recent call last):
  File "/Users/fhartavi/Desktop/tiktok2/example.py", line 4, in <module>
    username = os.environ['besoxur']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'besoxur'

**Comment by gordienko-dmitry** [comment]
make sure, that you set your environment variables
You can read about it https://en.wikipedia.org/wiki/Environment_variable

**Comment by reversebro** [comment]
Wikipedia in Turkey blocked if you help me I will be very happy 15-20 days I tried all python tiktok library I can't start working pls don't broken me and help me dear.

Thanks to you for this big library.

**Comment by gordienko-dmitry** [comment]
maybe it can help https://www.twilio.com/blog/2017/01/how-to-set-environment-variables.html
and this tiktok package like beta project, like prototype now, I've just starting to develop it
